name: www.slidize.ai
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@v4
      with:
          repository: smallize/slidize
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
          submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'
          extended: true
    - name: Determine Base URL
      id: base-url
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "::set-output name=url::https://www.slidize.ai"
        else
          echo "::set-output name=url::https://qa.slidize.ai"
        fi
    - name: Build 
      run: hugo --config "configs/slidize.ai/www.toml","configs/slidize.ai/common.toml" -b "https://www.slidize.ai" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Deploy
      run: hugo deploy --config "configs/slidize.ai/www.toml" --maxDeletes=-1 --target "production" --invalidateCDN --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
